#docker compose -f docker/docker-compose.yml up -d --build

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: smart_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_MODE: normal
      JWT_SECRET: dev_secret_change_me
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres_db?schema=public

volumes:
  postgres_data:
